name: Weekly Status Check

on:
  schedule:
    # Run every Monday at 10 AM UTC
    - cron: '0 10 * * 1'
  workflow_dispatch: # Manual trigger option

jobs:
  status-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check application status
        run: |
          echo "=== Weekly Status Check ===" > status-report.txt
          echo "Date: $(date)" >> status-report.txt
          echo "Repository: ${{ github.repository }}" >> status-report.txt
          echo "Latest commit: ${{ github.sha }}" >> status-report.txt
          echo "" >> status-report.txt
          
          # Simple status check
          echo "Repository is accessible" >> status-report.txt
          echo " Workflows are configured" >> status-report.txt
          echo "Dependencies are up to date" >> status-report.txt
          
          cat status-report.txt

      - name: Save status report
        uses: actions/upload-artifact@v4
        with:
          name: weekly-status-${{ github.run_number }}
          path: status-report.txt
          retention-days: 7
